### ISSUE TITLE
Fontawesome feedback icons not centered

### ISSUE THREAD

**Issue by 7rust** [1000hz/bootstrap-validator#254]
Hello, 
I've some trouble with adding font awesome icons as feedback to my forms. Using:

**HTML:**
    < div class="form-group" >
    < input type="text" required="" data-minlength="2" data-custom-autocomplete="off" maxlength="100" class="form-control" id="exampe" name="name" data-error="Message" placeholder="Abc"/>
    < span class="form-control-feedback" aria-hidden="true"></span>
    < /div >

**Config:**
```
feedback:
{
    success: "fa fa-check",
    error: "fa fa-close
}
```

![input](https://cloud.githubusercontent.com/assets/3810930/12143020/1aea9560-b47d-11e5-8b76-e2bc11841fc2.PNG)

EDIT: HTML was not shown.

**Comment by 7rust** [comment]
Temporary fix:
**CSS:**
```
.form-control-feedback
{
    right: 10px;
    top: 10px;
}
```

**Comment by 1000hz** [comment]
You're on your own for styling your own feedback icons since this plugin is deferring to Bootstrap's feedback classes.

**Comment by Kristories** [comment]
FYI for a good way, simply do this

``` html
<div class="form-group has-feedback">
    <label class="control-label">Label</label>
    <input type="text" class="form-control">
    <span class="form-control-feedback">
        <i class="fa fa-search"></i>
    </span>
</div>
```

OR with CSS

``` css
.fa.form-control-feedback {
    line-height: 34px;
}
.input-sm ~ .fa.form-control-feedback {
    line-height: 30px;
}
.input-lg ~ .fa.form-control-feedback {
    line-height: 46px;
}
```
