### ISSUE TITLE
Color issue using an input-group-btn

### ISSUE THREAD

**Issue by sunco007** [1000hz/bootstrap-validator#535]
I have a color issue when use an input-group-btn

You can see this in here: https://jsfiddle.net/5n2hex6h/5/

There is an input-group-**btn** and an input-group-**addon**

If click on submit, you can see the second one paints very well, but not the first one

**Comment by sunco007** [comment]
A workarround is to add this style and it work like a charm

``` css
.has-error .btn-default { border-color:#d62c1a; color:#d62c1a; }
```
